apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
#  namespace: dash-db
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: phpmyadmin
#  namespace: dash-db
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:edge-4.8  #@sha256:95b005cf4c5f15ff670a31f576a50db8d164c6692752bda6176af3fea0e60812
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: galera-db
